<?php

namespace ContainerYDlDDKA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HGuQ0HEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HGuQ0HE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HGuQ0HE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'courRepository' => ['privates', 'App\\Repository\\CourRepository', 'getCourRepositoryService', true],
        ], [
            'courRepository' => 'App\\Repository\\CourRepository',
        ]);
    }
}
