<?php

namespace ContainerYDlDDKA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_S44T0TiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.s44T0Ti' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.s44T0Ti'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cour' => ['privates', '.errored..service_locator.s44T0Ti.App\\Entity\\Cour', NULL, 'Cannot autowire service ".service_locator.s44T0Ti": it references class "App\\Entity\\Cour" but no such service exists.'],
            'quizRepository' => ['privates', 'App\\Repository\\QuizRepository', 'getQuizRepositoryService', true],
        ], [
            'cour' => 'App\\Entity\\Cour',
            'quizRepository' => 'App\\Repository\\QuizRepository',
        ]);
    }
}
