<?php

namespace ContainerN30CP2l;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XAl607jService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xAl607j' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xAl607j'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'questionRepository' => ['privates', 'App\\Repository\\QuestionRepository', 'getQuestionRepositoryService', true],
            'quiz' => ['privates', '.errored..service_locator.xAl607j.App\\Entity\\Quiz', NULL, 'Cannot autowire service ".service_locator.xAl607j": it references class "App\\Entity\\Quiz" but no such service exists.'],
        ], [
            'questionRepository' => 'App\\Repository\\QuestionRepository',
            'quiz' => 'App\\Entity\\Quiz',
        ]);
    }
}
