<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4XQoqge\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4XQoqge/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4XQoqge.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4XQoqge\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4XQoqge\App_KernelDevDebugContainer([
    'container.build_hash' => '4XQoqge',
    'container.build_id' => 'da85c7ac',
    'container.build_time' => 1709591346,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4XQoqge');
