<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYDlDDKA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYDlDDKA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYDlDDKA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYDlDDKA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYDlDDKA\App_KernelDevDebugContainer([
    'container.build_hash' => 'YDlDDKA',
    'container.build_id' => 'ecf90aee',
    'container.build_time' => 1709156748,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYDlDDKA');
